---
- name: Provision Demo Environment
  hosts: all
  gather_facts: false
  roles:
  - name: vagrant-common

- name: Install OpenLDAP
  hosts: openldapvm
  roles:
  - name: openldap

- name: Install ELK
  hosts: elkvm
  roles:
  - name: geerlingguy.java
  - name: geerlingguy.elasticsearch
  - name: ansible-role-logstash
    logstash_filters:
      - logstash.conf
  - name: geerlingguy.kibana

- name: Install and provision Ansible Tower
  hosts: towervm
  vars:
    towerpass: password1
    ldaplicense: false
  roles:
  - name: tower  

#  roles:
#    - { role: vagrant-common, when "'tag_Vagrant_True' in group_names" }
#    - { role: openldap, when: "'tag_Name_ldapvm' in group_names and ldaplicense == True" }
#    - { role: tower, when: "'tag_Name_Tower' in group_names" }
